import { describe, expect, it } from "vitest"
import { detectTextFormat } from "../src/_sniff"
import { read } from "../src/defter"

// ═══════════════════════════════════════════════════════════════════════
// `read()` sniffs a text format from the first non-whitespace characters
// (#469). Two of its answers were wrong, and the first one silently.
//
// **A leading comment meant HTML.** `<!--` was in the list of things that
// announce HTML, alongside a doctype and an `<html>` root. It does not
// announce anything — `<!-- Generated by … do not edit -->` heads a great
// many machine-written XML feeds. Those went to the HTML reader, which
// found no `<table>` and returned an **empty sheet**: no error, no rows,
// and the same document with its comment removed read fine.
//
// **`[` meant JSON outright**, on the stated grounds that an NDJSON file
// of arrays is "essentially unheard of, and reading it as JSON gives the
// same rows". The first half stands. The second does not: `[1,2]\n[3,4]`
// is not one JSON document, so reading it as JSON throws rather than
// giving the same rows. It is now decided by trying, like `{` already was.
// ═══════════════════════════════════════════════════════════════════════

const enc = new TextEncoder()
const sniff = (s: string): string | null => detectTextFormat(enc.encode(s))

const RECORDS = `<records>
  <record><name>Widget</name><qty>3</qty></record>
  <record><name>Gadget</name><qty>7</qty></record>
</records>`

describe("a leading comment does not decide the format", () => {
  it("xml behind a comment is still xml", () => {
    expect(sniff(`<!-- Generated by acme 1.2. Do not edit. -->\n${RECORDS}`)).toBe("xml")
  })

  it("and read() returns its rows, not an empty sheet", async () => {
    // The failure this fixes was silent, so the assertion is on the rows
    // rather than on the absence of a throw.
    const wb = await read(enc.encode(`<!-- Generated by acme 1.2. Do not edit. -->\n${RECORDS}`))

    expect(wb.sheets[0]!.rows).toEqual([
      ["name", "qty"],
      ["Widget", "3"],
      ["Gadget", "7"],
    ])
  })

  it("which is what the same document without the comment always did", async () => {
    const withComment = await read(enc.encode(`<!-- c -->${RECORDS}`))
    const without = await read(enc.encode(RECORDS))

    expect(withComment.sheets[0]!.rows).toEqual(without.sheets[0]!.rows)
  })

  it("html behind a comment is still html", () => {
    expect(sniff("<!-- licence header -->\n<!DOCTYPE html><html><body></body></html>")).toBe("html")
    expect(sniff("<!-- c --><html><body><table></table></body></html>")).toBe("html")
    expect(sniff("<!-- c --><table><tr><td>1</td></tr></table>")).toBe("html")
  })

  it("through several comments, and whitespace between them", () => {
    expect(sniff(`<!-- one -->\n\n  <!-- two -->\n<!-- three -->\n${RECORDS}`)).toBe("xml")
    expect(sniff("<!-- one --> <!-- two --> <html></html>")).toBe("html")
  })

  it("a comment containing markup does not confuse it", () => {
    // The comment body is not markup, however much it looks like it.
    expect(sniff(`<!-- <html><table> --><records><record/></records>`)).toBe("xml")
    expect(sniff(`<!-- <records> --><html><body/></html>`)).toBe("html")
  })

  it("an xml declaration after a comment still wins", () => {
    // Not legal XML — the declaration must come first — but a reader that
    // sniffs should not be the thing that rejects it.
    expect(sniff(`<!-- c -->\n<?xml version="1.0"?>${RECORDS}`)).toBe("xml")
  })

  it("an unterminated comment stays html, as it was", () => {
    // Only the first 4 KB are examined, so a comment longer than that has
    // nothing after it to look at. Unchanged behaviour, pinned so the
    // change above is visibly bounded.
    expect(sniff(`<!-- ${"x".repeat(5000)}`)).toBe("html")
  })
})

describe("json and ndjson are both decided by trying", () => {
  it("an array document is json", () => {
    expect(sniff('[{"a":1},{"a":2}]')).toBe("json")
    expect(sniff('[\n  {"a":1},\n  {"a":2}\n]')).toBe("json")
  })

  it("lines that are arrays are ndjson", () => {
    expect(sniff("[1,2]\n[3,4]\n")).toBe("ndjson")
  })

  it("and read() gets both rows out of it", async () => {
    const wb = await read(enc.encode("[1,2]\n[3,4]\n"))

    expect(wb.sheets[0]!.rows.length).toBeGreaterThanOrEqual(2)
  })

  it("objects behave as they always did", () => {
    expect(sniff('{"rows":[{"a":1}]}')).toBe("json")
    expect(sniff('{"a":1}\n{"a":2}\n')).toBe("ndjson")
  })

  it("a single unparseable line is still json, so the error names JSON", () => {
    // A truncated JSON file should fail as JSON rather than be quietly
    // read as something else.
    expect(sniff('{"a":1')).toBe("json")
    expect(sniff("[1,2")).toBe("json")
  })
})

describe("the formats around them are unchanged", () => {
  it("csv, tsv, plain xml and plain html", () => {
    expect(sniff("a,b,c\n1,2,3\n")).toBe("csv")
    expect(sniff("a\tb\tc\n1\t2\t3\n")).toBe("csv")
    expect(sniff('<?xml version="1.0"?><rows><row/></rows>')).toBe("xml")
    expect(sniff("<!DOCTYPE html><html></html>")).toBe("html")
    expect(sniff("")).toBeNull()
    expect(sniff("   \n ")).toBeNull()
  })

  it("binary is still refused", () => {
    expect(detectTextFormat(new Uint8Array([0x50, 0x4b, 0x03, 0x04, 0, 0, 0, 0]))).toBeNull()
  })
})
